### ISSUE TITLE
Installation via Composer

### ISSUE THREAD

**Issue by amsoell** [djmattyg007/official-library-php-email-parser#3]
What's the preferred way to load this into a project with composer? I see that packagist.com uses a fork of the original code, and I tried the following with no luck:

```
{
    ...
    "require": {
        "djmattyg007/official-library-php-email-parser": "*"
    },
    "repositories": [
       {
         "type": "vcs",
         "url": "https://github.com/djmattyg007/official-library-php-email-parser"
       }
    ],
   ...
}
```

**Comment by djmattyg007** [comment]
The name.of the package is `djmattyg007/emailparser`, as per the `composer.json` file: https://github.com/djmattyg007/official-library-php-email-parser/blob/master/composer.json

You should be able to install it from packagist without any issues.

**Comment by amsoell** [comment]
Excellent—thanks so much for keeping this alive and updated!

**Comment by djmattyg007** [comment]
No problem :)
